---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.npm

before_install:
  - npm config set spin false
<<<<<<< HEAD
  - npm install -g phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install

script:
=======

script:
  - npm run lint:js
>>>>>>> bc5cf5c... message
  - npm test
